# Don't print a new line at the start of the prompt
add_newline = false

# Replace the "â¯" symbol in the prompt with "âœ"
[character]                            # The name of the module we are configuring is "character"
success_symbol = "[âœ](bold green)"     # The "success_symbol" segment is being set to "âœ" with the color "bold green"
error_symbol = "[âœ—](bold red) "
vicmd_symbol = "[V](bold green) "

# Disable the package module, hiding it from the prompt completely
[package]
disabled = true

## Use custom format
#format = """
#[â”Œâ”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€>](bold green)
#[â”‚](bold green)$directory$rust$package
#[â””â”€>](bold green) """
#
## Wait 10 milliseconds for starship to check files under the current directory.
#scan_timeout = 10
#
## Disable the newline at the start of the prompt
#add_newline = false

#[hostname]
#ssh_only = false
#format =  "[$hostname](bold red) "
#trim_at = ".companyname.com"
#disabled = false

#[git_branch]
#symbol = "ğŸŒ± "
#truncation_length = 4
#truncation_symbol = ""
#
#[git_commit]
#commit_hash_length = 4
#tag_symbol = "ğŸ”– "
#
#[git_state]
#format = '[\($state( $progress_current of $progress_total)\)]($style) '
#cherry_pick = "[ğŸ’ PICKING](bold red)"
#
#[git_status]
#conflicted = "ğŸ³"
##ahead = "ğŸğŸ’¨"
##behind = "ğŸ˜°"
##diverged = "ğŸ˜µ"
#untracked = "ğŸ¤·"
#stashed = "ğŸ“¦"
#modified = "ğŸ“"
#staged = '[++\($count\)](green)'
#renamed = "ğŸ‘…"
#deleted = "ğŸ—‘"
#ahead = "â‡¡${count}"
#diverged = "â‡•â‡¡${ahead_count}â‡£${behind_count}"
#behind = "â‡£${count}"

#[directory]
#truncation_length = 8
#truncation_symbol = "â€¦/"
